apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: halo-theme-archer
spec:
  displayName: Archer
  version: 1.0.0
  author:
    name: fi3ework
    website: https://github.com/fi3ework
  description: A simple and modern theme for Halo.
  logo: /themes/halo-theme-archer/assets/Archer.webp
  website: https://github.com/Azincc/halo-theme-archer
  repo: https://github.com/Azincc/halo-theme-archer.git
  settingName: halo-theme-archer-setting
  configMapName: halo-theme-archer-configmap
  supportedVersions:
    - ">=2.11.0"
  license:
    - name: "CC BY-NC 4.0"
      url: "http://creativecommons.org/licenses/by-nc/4.0/"
